export const Claims = {
    REQUIRE_UPDATE: 'REQUIRE_UPDATE',
    PAYMENT_METHOD_ATTACHED: 'PAYMENT_METHOD_ATTACHED',
    MANAGE: 'MANAGE',
    CAN_ACCESS_CALCULATE: 'CAN_ACCESS_CALCULATE',
    CAN_ACCESS_HISTORICAL: 'CAN_ACCESS_HISTORICAL',
    CAN_ACCESS_USER_MANAGE: 'CAN_ACCESS_USER_MANAGE',
    CAN_ACCESS_USER_READ: 'CAN_ACCESS_USER_READ',
    CAN_ACCESS_USER_STATUS: 'CAN_ACCESS_USER_STATUS',
    CAN_ACCESS_USER_CREATE: 'CAN_ACCESS_USER_CREATE',
    CAN_ACCESS_USER_UPDATE: 'CAN_ACCESS_USER_UPDATE',
    CAN_ACCESS_USER_DELETE: 'CAN_ACCESS_USER_DELETE',
};